services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: quakes_db
      POSTGRES_USER: quakes_user
      POSTGRES_PASSWORD: quakes_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quake-net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quakes_user -d quakes_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./backend/backend.dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://quakes_user:quakes_password@db:5432/quakes_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quake-net
    volumes:
      - ./backend/earthquakes.geojson:/app/earthquakes.geojson
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./frontend/frontend_local.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - quake-net

volumes:
  postgres_data:

networks:
  quake-net:
    driver: bridge  