services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/frontend.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production  # Correct path for .env.production in the frontend folder
    depends_on:
      - backend
    networks:
      - quake-net
    restart: always  # Ensure the service restarts in case of failure

  backend:
    build:
      context: .
      dockerfile: ./backend/backend.dockerfile
    ports:
      - "8000:8000"  # Expose the backend on port 8000
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Ensure DATABASE_URL is passed from .env or the host
    networks:
      - quake-net
    volumes:
      - ./backend/data:/app/data  # Ensure data is persisted across container restarts
      - ./backend/geojson_files:/app/backend/geojson_files
    restart: always  # Ensure the service restarts in case of failure

networks:
  quake-net:
    driver: bridge
