services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/frontend.dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - quake-net

  backend:
    build:
      context: .
      dockerfile: ./backend/backend.dockerfile
    ports:
      - "8000:8000"
    networks:
      - quake-net
    volumes:
      - ./backend/earthquakes.geojson:/app/earthquakes.geojson

networks:
  quake-net:
    driver: bridge