services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/frontend.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production  # Correct path for .env.production in the frontend folder
    environment:
      - REACT_APP_API_URL=https://www.quakesnearme.com  # Using environment variable for API URL in production
    depends_on:
      - backend
    networks:
      - quake-net
    restart: always  # Ensure the service restarts in case of failure

  backend:
    build:
      context: .
      dockerfile: ./backend/backend.dockerfile
    ports:
      - "8000:8000"  # Expose the backend on port 8000
    networks:
      - quake-net
    volumes:
      - ./backend/earthquakes.geojson:/app/earthquakes.geojson
    restart: always  # Ensure the service restarts in case of failure

networks:
  quake-net:
    driver: bridge
