services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: ["python", "main.py"]

  frontend:
    build:
      context: ./quakes-app
    volumes:
      - ./quakes-app:/srv/app/fr-shohin-admin-client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
