services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/frontend.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - quake-net

  backend:
    build:
      context: .
      dockerfile: ./backend/backend.dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///app/data/quakes_near_me.db
    networks:
      - quake-net

networks:
  quake-net:
    driver: bridge