name: CI/CD Pipeline for Production

on:
  push:
    branches:
      - master  # Triggers the pipeline when code is pushed to 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Create .env.production for frontend (add Mapbox token and API URL)
      - name: Set up .env.production in frontend
        run: |
          echo "REACT_APP_API_URL=${{ secrets.PROD_REACT_APP_API_URL }}" > ./frontend/.env.production
          echo "REACT_APP_MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" >> ./frontend/.env.production

      # Debugging step to check .env.production file
      - name: Debugging .env.production file
        run: cat ./frontend/app/.env.production

      # Build and run Docker containers for production
      - name: Build and run Docker containers
        run: |
          docker-compose -f docker-compose.prod.yml down  # Stop any existing container
          docker-compose -f docker-compose.prod.yml up --build -d  # Use production Docker Compose file

      # Deployment to production server
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_Key }}

      - name: Deploy to Production Server
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.23.177.89 << 'EOF'
            cd quakes-near-you
            echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> .env  # Backend uses root-level .env
            git pull
            docker-compose -f docker-compose.prod.yml down  # Stop existing containers
            docker-compose -f docker-compose.prod.yml up --build -d  # Rebuild and deploy the updated containers
          EOF
