name: CI/CD Pipeline for Production

on:
  push:
    branches:
      - master  # Triggers the pipeline when code is pushed to 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Create .env.production for frontend (add Mapbox token and API URL)
      - name: Set up .env.production in frontend
        run: |
          echo "REACT_APP_API_URL=${{ secrets.PROD_REACT_APP_API_URL }}" > ./frontend/.env.production
          echo "REACT_APP_MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" >> ./frontend/.env.production
          ls -al  # List the files to verify the .env exists

      - name: Verify .env.production file
        run: |
          ls -l ./frontend/.env.production
          cat ./frontend/.env.production

      # Build and run Docker containers for production
      - name: Build and run Docker containers
        run: |
          docker-compose -f docker-compose.prod.yml down  # Stop any existing container
          docker-compose -f docker-compose.prod.yml build \
            --build-arg REACT_APP_API_URL=${{ secrets.PROD_REACT_APP_API_URL }} \
            --build-arg REACT_APP_MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}
          docker-compose -f docker-compose.prod.yml up --build -d  # Use production Docker Compose file