name: CI/CD Pipeline for Production

on:
  push:
    branches:
      - master  # Triggers the pipeline when code is pushed to 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Prepare Environment File (Optional)
      - name: Create .env file (optional)
        run: |
          cp .env.production .env  # Ensure production environment variables
          ls -al  # Verify that the .env exists

      # Add SSH key for deployment
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_Key }}

      # Deploy to Production Server
      - name: Deploy to Production Server
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.23.177.89 << 'EOF'
            cd quakes-near-you
            git pull origin master  # Pull the latest code from the master branch
            echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" > .env  # Recreate .env file
            echo "REACT_APP_API_URL=${{ secrets.PROD_REACT_APP_API_URL }}" >> .env
            docker-compose -f docker-compose.prod.yml pull  # Pull latest images
            docker-compose -f docker-compose.prod.yml up --build -d  # Build and restart containers
            docker system prune -f  # Clean up unused Docker objects
          EOF
